### ISSUE TITLE
Missing network "shufflenetg2" and trained network weights: ./checkpoint/%s/ckpt.t7

### ISSUE THREAD

**Issue by scc-zju** [AaronHeee/MEAL#3]
I can't find some networks, such as  "shufflenetg2", and trained network weights: ./checkpoint/%s/ckpt.t7.
Could you provide the code with necessary files, which can be excuted successfully? Thanks.
I fixed some bugs, but it still can't run. 
---
Namespace(adv=1, base_channels=96, base_lr=0.2, batch_size=128, d_lr=0.1, depth=26, epochs=1800, eta='[1,1,1,1,1]', fc_out=1, gamma='[1,1,1,1,1]', gpu_id='0', loss='ce', lr=0.1, lr_min=0, momentum=0.9, name=None, nesterov=True, num_workers=7, out_dims='[5000,1000,500,200,10]', out_layer='[-1]', outdir='results', pool_out='max', resume=False, seed=17, shake_backward=True, shake_forward=True, shake_image=True, student='resnet18', teacher_eval=0, teachers="['resnet18']", weight_decay=0.0001)
==> Preparing data..
Files already downloaded and verified
Files already downloaded and verified
==> Training resnet18
==> Building model..
Traceback (most recent call last):
  File "main.py", line 164, in <module>
    teachers, student = get_model(args, config, device="cuda")
  File "MEAL/utils.py", line 173, in get_model
    checkpoint = torch.load('./checkpoint/%s/ckpt.t7' % teacher.__name__)
  File "py3torch041/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './checkpoint/resnet18/ckpt.t7'

**Comment by Vincent-Hoo** [comment]
Can you find the "shake_shake_main" file? Do you just comment the lines related to "shake_shake"?

**Comment by scc-zju** [comment]
@Vincent-Hoo 
I can't find "shake_shake_main" file too, so I just comment the import line about "shake_shake".
I fix the import bug as follow.
'# from shake_shake_main import str2bool, load_model, get_cosine_annealing_scheduler

def str2bool(v):
    return v.lower() in ("yes", "true", "t", "1")
'

**Comment by aditipanda** [comment]
I can't find these files either. Even init.py doesnot work because lenet is absent.
Are we just supposed to comment everything that's absent ?

**Comment by szq0214** [comment]
Hi all, sorry for the trouble aroused by our negligence. I will upload the pre-trained models soon.

**Comment by szq0214** [comment]
Hi all, please check https://github.com/AaronHeee/MEAL/commit/2210139d708b31604d07e0c71bd5888af9dd6885.

**Comment by appyfizzA** [comment]
> Hi all, please check [2210139](https://github.com/AaronHeee/MEAL/commit/2210139d708b31604d07e0c71bd5888af9dd6885).

Thank you, @szq0214 
But "shake_shake_main" is still not there.

**Comment by baiyancheng20** [comment]
@szq0214 Could you add the shake_shake_main.py file? Thank you.

**Comment by xiaoyuxie-vico** [comment]
I can't find these files(shake_shake_main) either.

**Comment by yongqiangzhang1** [comment]
@szq0214 , how to solve the error ```ModuleNotFoundError: No module named 'shake_shake_main```? Could you please upload the file "shake_shake_main", thanks.
