### ISSUE TITLE
Access denied error

### ISSUE THREAD

**Issue by aditipanda** [AaronHeee/MEAL#5]
When I run main.py I get this error:

**Epoch: 0
Traceback (most recent call last):

  File "<ipython-input-1-93d2c00ecd1c>", line 1, in <module>
    runfile('G:/Aditi/Steel_Image_Edge_Detection/MEAL/MEAL-master/main.py', wdir='G:/Aditi/Steel_Image_Edge_Detection/MEAL/MEAL-master')

  File "C:\Users\Aditi_Panda\Anaconda3\Lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Users\Aditi_Panda\Anaconda3\Lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "G:/Aditi/Steel_Image_Edge_Detection/MEAL/MEAL-master/main.py", line 332, in <module>
    train(epoch)

  File "G:/Aditi/Steel_Image_Edge_Detection/MEAL/MEAL-master/main.py", line 245, in train
    for batch_idx, (inputs, targets) in enumerate(trainloader):

  File "C:\Users\Aditi_Panda\Anaconda3\Lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)

  File "C:\Users\Aditi_Panda\Anaconda3\Lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()

  File "C:\Users\Aditi_Panda\Anaconda3\Lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)

  File "C:\Users\Aditi_Panda\Anaconda3\Lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "C:\Users\Aditi_Panda\Anaconda3\Lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)

  File "C:\Users\Aditi_Panda\Anaconda3\Lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)

  File "C:\Users\Aditi_Panda\Anaconda3\Lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)

  File "C:\Users\Aditi_Panda\Anaconda3\Lib\multiprocessing\synchronize.py", line 105, in __getstate__
    h = context.get_spawning_popen().duplicate_for_child(sl.handle)

  File "C:\Users\Aditi_Panda\Anaconda3\Lib\multiprocessing\popen_spawn_win32.py", line 72, in duplicate_for_child
    return reduction.duplicate(handle, self.sentinel)

  File "C:\Users\Aditi_Panda\Anaconda3\Lib\multiprocessing\reduction.py", line 76, in duplicate
    0, inheritable, _winapi.DUPLICATE_SAME_ACCESS)

PermissionError: [WinError 5] Access is denied**

**Comment by aditipanda** [comment]
Tried to run this from administrator command prompt, got the following error:

Failed to import the site module
Traceback (most recent call last):
  File "C:\Users\Aditi_Panda\Anaconda3\Lib\site-packages\site.py", line 73, in <module>
    __boot()
  File "C:\Users\Aditi_Panda\Anaconda3\Lib\site-packages\site.py", line 47, in __boot
    addsitedir(item)
  File "C:\Users\Aditi_Panda\Anaconda3\lib\site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "C:\Users\Aditi_Panda\Anaconda3\lib\site.py", line 162, in addpackage
    for n, line in enumerate(f):
  File "C:\Users\Aditi_Panda\Anaconda3\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1353: character maps to <undefined>

python is properly installed on my windows system, when I type python on cmd, it gives:
Python 3.5.6 |Anaconda, Inc. .....

But if I change the folder to MEAL-master, this error comes.  Please help.
